#!/bin/sh
#
# @name Tilting quadrotor
#
# @type Tilting Multirotor
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @output AUX1 motor 1
# @output AUX2 motor 2
# @output AUX3 motor 3
# @output AUX4 motor 4
#
# @maintainer Salvatore Marcellini <salvatore.marcellini@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

# param set-default SYS_CTRL_ALLOC 1 #dynamic allocation
param set-default CA_AIRFRAME 13 #Tilting Multirotor
param set-default CA_TILTING_TYPE 1 #Omnidirectional tilting drone

set MAV_TYPE 14

# Set all 8 channels
set PWM_OUT 1234
set PWM_AUX_OUT 1234
param set-default CA_ROTOR_COUNT 4
param set-default CA_SV_TL_COUNT 4

#X-forward, Y-right
param set-default CA_ROTOR0_PX 0.17 #M1 CCW
param set-default CA_ROTOR0_PY 0.17
param set-default CA_ROTOR0_PZ 0.00
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX 0.17 #M2 CW
param set-default CA_ROTOR1_PY -0.17
param set-default CA_ROTOR1_PZ 0.00
param set-default CA_ROTOR1_KM -0.05

param set-default CA_ROTOR2_PX -0.17 #M3 CCW
param set-default CA_ROTOR2_PY -0.17
param set-default CA_ROTOR2_PZ 0.00
param set-default CA_ROTOR2_KM 0.05

param set-default CA_ROTOR3_PX -0.17 #M4 CW
param set-default CA_ROTOR3_PY 0.17
param set-default CA_ROTOR3_PZ 0.00
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101 #esc
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default PWM_MAIN_FUNC9 201 #servo
param set-default PWM_MAIN_FUNC10 202
param set-default PWM_MAIN_FUNC11 203
param set-default PWM_MAIN_FUNC12 204

# Limits for tilting angles
param set-default CA_SV_TL0_MAXA 30
param set-default CA_SV_TL0_MINA -30
param set-default CA_SV_TL1_MAXA 30
param set-default CA_SV_TL1_MINA -30
param set-default CA_SV_TL2_MAXA 30
param set-default CA_SV_TL2_MINA -30
param set-default CA_SV_TL3_MAXA 30
param set-default CA_SV_TL3_MINA -30


